### ISSUE TITLE
ModuleNotFoundError: No module named 'ignis.main'

### ISSUE THREAD

**Issue by trolljoe** [linkfrg/ignis#8]
trying to run ignis to make my own service, but running `ignis init` outputs:

```
Traceback (most recent call last):
  File "/usr/bin/ignis", line 4, in <module>
    from ignis.main import main
ModuleNotFoundError: No module named 'ignis.main'
```
from the beginning though, it also complained about other missing packages (that weren't included in the requirements.txt), those being:

ignis
torch
numpy

installing these fixed most of the modulenotfound, but this one doesn't seem to go away. ignis will also only run when i'm on a venv.

**Comment by linkfrg** [comment]
ummm, Ignis doesn't use numpy and pytorch. How do you installed Ignis?

**Comment by trolljoe** [comment]
> ummm, Ignis doesn't use numpy and pytorch. How do you installed Ignis?

i've simply git cloned the repo, did meson setup, meson build and meson install.

**Comment by linkfrg** [comment]
Are you trying to set up a development environment? If yes, follow this guide: https://linkfrg.github.io/ignis/stable/dev/env.html

**Comment by trolljoe** [comment]
> Are you trying to set up a development environment? If yes, follow this guide: https://linkfrg.github.io/ignis/stable/dev/env.html

i've tried, but trying to run main.py gives me:

```
Traceback (most recent call last):
  File "/home/joetroll/git-clone/ignis/ignis/main.py", line 2, in <module>
    from ignis.cli import cli
  File "/home/joetroll/git-clone/ignis/venv/lib/python3.12/site-packages/ignis/__init__.py", line 1, in <module>
    import gi
  File "/home/joetroll/git-clone/ignis/venv/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
  File "/usr/lib/python3.12/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.12/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/lib/python3.12/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/home/joetroll/git-clone/ignis/ignis/logging.py", line 3, in <module>
    from loguru import logger
  File "/home/joetroll/git-clone/ignis/venv/lib/python3.12/site-packages/loguru/__init__.py", line 10, in <module>
    from ._logger import Core as _Core
  File "/home/joetroll/git-clone/ignis/venv/lib/python3.12/site-packages/loguru/_logger.py", line 99, in <module>
    from . import _asyncio_loop, _colorama, _defaults, _filters
  File "/home/joetroll/git-clone/ignis/venv/lib/python3.12/site-packages/loguru/_asyncio_loop.py", line 27, in <module>
    get_task_loop, get_running_loop = load_loop_functions()
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joetroll/git-clone/ignis/venv/lib/python3.12/site-packages/loguru/_asyncio_loop.py", line 11, in load_loop_functions
    get_running_loop = asyncio.get_running_loop
                       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'asyncio' has no attribute 'get_running_loop' (most likely due to a circular import)
```

**Comment by trolljoe** [comment]
i know my window manager supports layer-shell, as AGS works fine.

**Comment by linkfrg** [comment]
very strange, have you tried installing Ignis the usual way?
Also what distro you use?

**Comment by trolljoe** [comment]
> very strange, have you tried installing Ignis the usual way? Also what distro you use?

yeah, gives off the same error. i'm on gentoo glibc, i've removed the GTK version check for now and see if itll work without that

**Comment by trolljoe** [comment]
i got it working. the gtk layer shell was in /usr/local/lib64/ginspect/Gtk4LayerShell, so i moved it to /usr/lib64/ginspect. kinda of a bad fix but it'll do for now.

**Comment by salahoued** [comment]
same issue as above,
there are no /usr/local/lib64/ginspect/Gtk4LayerShell, /usr/lib64/ginspect on my system (openSUSE Tumblweed)

and I installed it the way it is shown in the installation guide for installing from source, without any issues

**Comment by EisregenHaha** [comment]
i still got the same on fedora, no package so built from source and it wants torch which is a full gigabyte so im confused asf
