### ISSUE TITLE
unable to init

### ISSUE THREAD

**Issue by shadowe1ite** [linkfrg/ignis#9]
```
ignis init            

(python3:38070): Gtk-WARNING **: 10:46:51.330: Theme parser error: gtk.css:506:72-73: linear-gradient() requires at least 3 arguments

(python3:38070): Gtk-WARNING **: 10:46:51.330: Theme parser error: gtk.css:558:72-73: linear-gradient() requires at least 3 arguments

(python3:38070): Gtk-WARNING **: 10:46:51.330: Theme parser error: gtk.css:627:74-75: linear-gradient() requires at least 3 arguments

(python3:38070): Gtk-WARNING **: 10:46:51.338: Theme parser error: gtk.css:4216:72-73: linear-gradient() requires at least 3 arguments

(python3:38070): Gtk-WARNING **: 10:46:51.340: Theme parser error: gtk.css:5557:3-9: No property named "height"

(python3:38070): Gtk-WARNING **: 10:46:51.341: Theme parser error: gtk.css:6252:72-73: linear-gradient() requires at least 3 arguments
2024-10-01 10:46:51 [INFO] Using configuration file: /home/shadow/.config/ignis/config.py
2024-10-01 10:46:51 [ERROR] ModuleNotFoundError: No module named 'services.material'; 'services' is not a package
Traceback (most recent call last):

  File "/usr/bin/ignis", line 5, in <module>
    main()
    └ <function main at 0x7a70a78a9800>
  File "/usr/lib/python3.12/site-packages/ignis/main.py", line 12, in main
    cli()
    └ <OrderedGroup cli>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7a70a5068fe0>
           └ <OrderedGroup cli>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7a70a053a810>
         │    └ <function MultiCommand.invoke at 0x7a70a506a200>
         └ <OrderedGroup cli>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7a70a04a8560>
           │               │       │       └ <function Command.invoke at 0x7a70a5069bc0>
           │               │       └ <Command init>
           │               └ <click.core.Context object at 0x7a70a04a8560>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7a70a781ca40>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'config': '~/.config/ignis/config.py', 'debug': False}
           │   │      │    │           └ <click.core.Context object at 0x7a70a04a8560>
           │   │      │    └ <function init at 0x7a70a022f560>
           │   │      └ <Command init>
           │   └ <function Context.invoke at 0x7a70a5068540>
           └ <click.core.Context object at 0x7a70a04a8560>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'config': '~/.config/ignis/config.py', 'debug': False}
                       └ ()
  File "/usr/lib/python3.12/site-packages/ignis/cli.py", line 72, in init
    run_app(config_path, debug)
    │       │            └ False
    │       └ '/home/shadow/.config/ignis/config.py'
    └ <function run_app at 0x7a70a022fba0>
  File "/usr/lib/python3.12/site-packages/ignis/app.py", line 432, in run_app
    app.run(None)
    │   └ <function Application.run at 0x7a70a50723e0>
    └ <app.IgnisApp object at 0x7a709bf11280 (ignis+app+IgnisApp at 0x5b7a9bfabc10)>
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
           │   │           │   │      │       └ {}
           │   │           │   │      └ (None,)
           │   │           │   └ <app.IgnisApp object at 0x7a709bf11280 (ignis+app+IgnisApp at 0x5b7a9bfabc10)>
           │   │           └ gi.FunctionInfo(run, bound=None)
           │   └ <class 'gi.repository.Gio.Application'>
           └ <IntrospectionModule 'Gio' from '/usr/lib/girepository-1.0/Gio-2.0.typelib'>
> File "/usr/lib/python3.12/site-packages/ignis/app.py", line 270, in do_activate
    __import__(config_filename)
               └ 'config'

  File "/home/shadow/.config/ignis/config.py", line 7, in <module>
    from modules.control_center import control_center  # noqa: E402

  File "/home/shadow/.config/ignis/modules/control_center/__init__.py", line 4, in <module>
    from .quick_settings import quick_settings

  File "/home/shadow/.config/ignis/modules/control_center/quick_settings.py", line 5, in <module>
    from .dark_mode import dark_mode_button

  File "/home/shadow/.config/ignis/modules/control_center/dark_mode.py", line 1, in <module>
    from services.material import MaterialService

ModuleNotFoundError: No module named 'services.material'; 'services' is not a package
```

**Comment by linkfrg** [comment]
dotfiles issue, reopen issue in the dotfiles repo
